# Site settings
title: Alex Bloom
email: hello@alexbloom.co
author: Alex Bloom
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_username: alexanderlbloom
twitter_username: alexbloom
instagram_username: alexbloom
dribbble_username: alexbloom
tumblr_username: alexbloom
medium_username: alexbloom
github_username: alexbloom

collections: projects
collections:
  projects:
    output: true
    permalink: /projects/:path/

#sass:
    #style: compressed

#assets:
# compress:
#   css: true
  # js: false | true | default - development: false, production: true
# cache: false | directory | default: .asset-cache
# prefix: "/assets"
# assets:
#   - "*.png"
#   - "bundle.css"
# digest: true
# sources:
#   - "_assets/folder"

# Build settings
markdown: kramdown

# Exclusions from Build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - .sass-cache
# exclude: [gulpfile, .sass-cache]
